[install]
package = mgutenberg
catalogues = mgutenberg; extras; fbreader

[catalogues]
catalogues = mgutenberg; extras; fbreader

[mgutenberg]
name = MGutenberg etc. catalogue
uri = http://www.elisanet.fi/ptvirtan/repo/
components = main

[extras]
name = maemo Extras
uri = http://repository.maemo.org/extras/
components = free non-free

[fbreader]
name = FBReader
uri = http://www.fbreader.org/maemo/
components = user
