#!/usr/bin/env python2.5
import sys, os
PD = os.path.join(os.path.dirname(__file__), '..')
if os.path.isfile(os.path.join(PD, 'mgutenberg', '__init__.py')):
    sys.path.insert(0, PD)
from mgutenberg.main import main
main()
